### PR TITLE
Adding New Property PaymentReceipt

### PR DESCRIPTION
**Pull request by SN185205**
Adding New Property PaymentReceipt to GetTotalsResponse Class

## Tested scenarios

**Fixed issue**:

### CODE REVIEW

**Comment by SN185205** [comment]
we are excepting similar behavior as Store Value response for getting Payment Receipt in GetTotalsResponse. This will help us to get reconciliation totals receipt. Currently we are not sure whether this will work, but would like give a try. please let us know you are thoughts.

**Comment by AlexandrosMor** [comment]
Hello @SN185205,

Thank you for opening this PR, I would like to ask if the PaymentReceipt is needed in the GetTotalsResponse. If you could post the json GetTotalsResponse that you receive from the terminal that would be great. 

kind regards,
Alexandros
Adyen

**Comment by SN185205** [comment]
2020-09-23 12:56:13,327 [FSM_TERM2] DEBUG - Response: 
{ "SaleToPOIResponse": { "SecurityTrailer": { "AdyenCryptoVersion": 1, "Nonce": "4PJciwzsW3ayJkt\/Vf4\/FQ==", "KeyIdentifier": "ncrkey", "Hmac": "MIn+1ffGqw29MLWBysTwPsafGh9D36AuRa7DXtJB96c=", "KeyVersion": 0 }, "NexoBlob": "RPwrppjNtArvX46Nnpjtj3BuqCPDxsg4cdMaBPP09nj\/ITfDIpZyU3V+ZVMfV+EvWlpXA0EHxCsilbs\/1ML\/\/rsUqjKcw1CJRkjrUOao6HOwLcWiyKrrjWM82pI3F5b\/sBZLbh9J4EqzJ+HPzj\/CTKUqLdFOr1XSD58OxzMdvYVm9kMrKO7u1fDO0geU1f5lLM4Y3nR9VAUhSQJnjlDs0W5DWCVmnQEUMsPu7G\/EBVvX0saO\/SP9CCCjE9CIGvkgGoKnjcq0X+g4zZcNDbNJ2ZbBt6wPjrQOCSAus5com3NNDDwuNREuWtIgioAJ0nWFOEttB3ddotfKJAYW8BmvgwOU+jhakurXNK8nxMdTIpkfTvS2AuX+aFRTS7l5YALYfsEF+c1pxRouIcPgGVGRzmfSxTj945xzqgyJUkUryzCEGdSZsdckKnqD\/J6K7K\/wJnlAzCtApV2dzmzz3QxknGe+OLdLEI7lHs93me2BbA2UirdU3nNCBHWjS+kuuiCllk6JluFt3XelZtxXkmQ8+6Kkwf3j4cZPA4h2v3S4NdNzrjFQjaLgaWVCCjzqzUQIGa+tLlpkhDokJowZ8uJqvczhaCz\/gIRM65Z5x+aVXwT7922kRp06pbGSoiCJfhicoeVik\/khdOzGRsp4bhsRfYKuwnWsLqH62ynNqhgBElz4V0lmp\/s9wJHLsL3UraFF4\/KqUkjpcGLtEHH5pi3Jc9o3uSUUODVI0jUa4PzXYBHiix2mQy\/PfUXVyx5YGiCBPBzPQgpSzGrmLApbT2B90ijCJEba4cshkUKVDrkJVDk3ulxMDA0QeyomqLP\/An37RnHekpwW6Vzs4mT6j83OqqTLkZ9pIkcwoMHPQEfE8t19NyMCIGwRK5EKBh1\/kkj\/V6YJInPs9QRThOCaLvy4AfCHo3NqitwCBa1PiY4bqbGzKgmM6AfcvA78E3WFWil3UicUyitFsJz3v9WaxZ\/EtQv5A8euaP4HAMqEP8YucYmqizcYv+pXnz4Sz97EgzDMgfB2+dwBxOIoMamInNRih0P9t7BPTCGmeSks1l5QILtQ5A8tJT9a86BpCiz23C39ph9IPWRorwz8EMa45zKVue+iykG19DmdLtaOh5XSVqUlnKgF8h4ypAswcQjFC879A+lWfMKGMWkkLg5feWxCQtkBs6H6vuy6tsk2f+uJpo5cQUjxbkhP0TNvIFd3e3rjUF0R1L95k++EdfradNj57yh8DedExwx3x7AuNEeKFrxuqJSHIgp8gCtK\/sR929SmNLzE4P9voEXfFX2wqgUHY\/EVaeimA40Gf55X3H\/NsgdzMqhdhfDo2NN+hQshlke73Y1Q3BktxetFwTO2SerBujGpmKGtVWOOoq+aw79VRvsUYoAFyRAeIJFmjUHqDSz2Kkbtge4F9eP3DiWyDOeuSzqI4ZnTQHpA2bfTtRJgHCsJ3kJ1qkMNeL5Xjaj8iN1Rki5fF4nIQuKi4DFbLZ73B241c1waHTNfCVKEIGwrcfMfWR5m2aDytZS7MlaZ+2BZuB6ghcEGgTcyqjhK2sGhU73mCmbthMYwAWdyfmVn8Ukq8c5E6RHgB1in6CmN+KCE7i6q5MlyDQqiEn8cINRNz+4fotahgcmGjKb2i8WYcvIxQSmX5IEpq6MnOXoiq2ePzQLd+KcVnXfpouz9cROTE1xQ1bWVfDdfA14nMwIm\/ARx04NppZ8UTUhbucr8PEBRKR2aN+CEicy+l0neM3GLoM5SEg4RM7Z0ks7pBpxUqIACdfjJexHCYoRRKBKRln9vYFzRQGmiR3RjYxuPeUBGDD1MS8SnY9sj+9alJOrXT30voFdbTu+w\/6sQTA6S3Y67hME6FQBcotzWoryOmHzjPCR8sjOjh30EwktYCzJLqlvjiK3iG1\/f4Ly5LgTf97xYZpzjrbQHclSmSTiCwcghQ8mQDuCC4sRzSjsQsgsPGKSC3UeZSeYZKf7zvDNBEAqSQM1yznm2ms17WC\/Spmko1JKQ5PP5EgX4v9ddBGpxL\/fr51Tri0sDdM\/1vWcPelo3QJMHg3842uTBYL99O40VnUB6mstkhF04lCxuuQoNuMKfumHAKJCiofafqutDljI7lKxbSyhJVujeA+YpdiAHvJ5\/F7HXiw1U1kgfQ9IFEVicgl0\/lOH6IjnE9EdKbrABaUTvggTLzVY0TO0JKr4RyluLaQ6rz8cSfGLOG+TgYS4Ppbbss45G2IRT\/Hi8l0YyCD9056Oo9HDXwAzX4sqyvSs2VWNVWWEElcIbwP6MtvitxZnPlPRyYn3AHXVTwuc711Gog9a58aWzGsI\/fxLowkURMcaboItIDIsLyEIzfMti7qHy3AGkZ02zeYd32LEHkU0O20cHxauNdVMcARSY8Uh1CTINdZLtIwwN\/6dRo20I0TWKqhQ26vH88FSTDkYzhtpCqcf5DvrG51vtN8gBxY5Pz91Hex5tCBFjJRV8R\/0PyjZw84ZUZW6X5vLHDGkSkoWe3Oq8e7y8HLJbpKtUYikDYjls+kCxhEWyw9xerpDxN814jwee+KxJoJq5mPUqD3JMMmdi\/VKjOlyzkM48Af1PFLVO38ZUUT84xIo8tApW7fV8UoyNspfBZuTLFlY\/ylzuE072Ef2HrTfujHuebmQc2AtZUSRGs4CYtSHQfNZvZVySsxJ\/7cAelrJGEtTedwYVMqK9QJR67phlTea08IZ43sC6hXXhqZ21qYd9MNGoe9EgRpnnGNwTuR3LqurHfMm5iLVwRIyT07f+ifCuJ7Ug+eVAfTxKrvDw5C6JjWXyYMhwH1QT4PlLfoIKuB+j1LDWE5Y1cVLw9reLVnT8gmLfj6SRdaE0\/apP9T0HH2Xac\/9u6igQkpJMnLD7jlaTn6CuasJhAKVg251F8cLjGEgBydsm82CH7GjYqU44l9Wt\/rykfn7+\/w11+1vx5v\/nK4L0iXWemui5DL5RgAr6Upv5oDP7hb6aOr0UPcd+PYpHyD8K5KfvsViAi3RVseFs51DZNWTicfn0wZrIo\/GAeXfT1CXEa0h3HDsrEOHTlUb89\/p+dU98rS16zSEHR5\/T8Mn5U7yajviWBSURR7M8lqSquDsTPVYwEX+fnQgU6Y32lcHLeYy7Ocgr5ZbFc0MUY63JtsZWtAcx6\/9IbFedyULZo1otWMB9CO1nwcIxht2w3veIb9I1tkpv1TTmDd2ReMmG8Nb4TWH2dkRJLThgqiuqiZf2xjKtjdtB01fvSueX0PsjizFmb21YGs02IzEfcZ00K7\/5Sd9rpqwj+UeBjEv6yXlmoFR7NX+RmlxqIjY=", "MessageHeader": { "SaleID": "2", "MessageClass": "Service", "MessageCategory": "GetTotals", "ServiceID": "2300200483", "POIID": "P400Plus-275102925", "MessageType": "Response" } } }

**Comment by AlexandrosMor** [comment]
Please adjust the fields with dummy data :)

**Comment by AlexandrosMor** [comment]
@

**Pull request closed without merging**
